import React, { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { apiCached } from '../../services/apiClient';
import type { PlanDetailProps } from '../../navigation/types';
import type {
  CurrentPlanResponse,
  PlanDayData,
  PlanBlock,
  PlanExercise,
} from '../../types/api';

const MONO = Platform.OS === 'ios' ? 'Menlo' : 'monospace';
const DAYS = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];

export default function PlanDetailScreen({ navigation }: PlanDetailProps) {
  const insets = useSafeAreaInsets();
  const [loading, setLoading] = useState(true);
  const [plan, setPlan] = useState<CurrentPlanResponse | null>(null);
  const [expandedDay, setExpandedDay] = useState<string | null>(null);

  useFocusEffect(
    useCallback(() => {
      (async () => {
        setLoading(true);
        try {
          const body = await apiCached<CurrentPlanResponse>(
            '/api/plans/current',
            'cache_plans_current',
          );
          setPlan(body);
          // Auto-expand today
          const today = body.week?.find((d) => d.today);
          if (today) setExpandedDay(today.date);
        } catch {
          // non-fatal
        } finally {
          setLoading(false);
        }
      })();
    }, []),
  );

  const toggleDay = (date: string) => {
    setExpandedDay((prev) => (prev === date ? null : date));
  };

  return (
    <View style={[styles.root, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <Pressable onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Text style={styles.backText}>{'<'} BACK</Text>
        </Pressable>
        <Text style={styles.headerTitle}>YOUR PLAN</Text>
        <View style={styles.backBtn} />
      </View>

      {loading ? (
        <View style={styles.center}>
          <ActivityIndicator color="#555555" />
        </View>
      ) : !plan || !plan.week || plan.week.length === 0 ? (
        <View style={styles.center}>
          <Text style={styles.emptyTitle}>NO PLAN GENERATED</Text>
          <Text style={styles.emptyText}>
            Complete onboarding and log your first workout so our AI can build a
            personalized training plan for you.
          </Text>
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={[
            styles.scrollContent,
            { paddingBottom: insets.bottom + 32 },
          ]}>
          {plan.plan && (
            <View style={styles.planMeta}>
              <Text style={styles.planName}>{plan.plan.name}</Text>
              <Text style={styles.planType}>
                {plan.plan.training_type.replace(/_/g, ' ').toUpperCase()}
              </Text>
              <Text style={styles.aiLabel}>AI-GENERATED PLAN</Text>
              <Text style={styles.aiExplainer}>
                This plan is dynamically generated by our AI based on your
                training history, recovery data, and goals. It adapts each week
                as you train.
              </Text>
            </View>
          )}

          {plan.week.map((day) => {
            const isExpanded = expandedDay === day.date;
            const d = new Date(day.date + 'T00:00:00');
            const dayLabel = DAYS[d.getDay()];
            const dateLabel = `${d.getMonth() + 1}/${d.getDate()}`;
            const sessionLabel = day.rest_day
              ? 'REST'
              : day.session_type.replace(/_/g, ' ').toUpperCase();
            const isCompleted = day.workout_status === 'completed';

            return (
              <View key={day.date}>
                <Pressable
                  style={[
                    styles.dayRow,
                    day.today && styles.dayRowToday,
                    isExpanded && styles.dayRowExpanded,
                  ]}
                  onPress={() => toggleDay(day.date)}>
                  <View style={styles.dayInfo}>
                    <Text
                      style={[
                        styles.dayLabel,
                        day.today && styles.dayLabelToday,
                      ]}>
                      {dayLabel}
                    </Text>
                    <Text style={styles.dayDate}>{dateLabel}</Text>
                  </View>
                  <Text
                    style={[
                      styles.daySession,
                      day.rest_day && styles.dayRest,
                    ]}>
                    {sessionLabel}
                  </Text>
                  <View style={styles.dayStatus}>
                    {isCompleted && (
                      <Text style={styles.checkmark}>{'✓'}</Text>
                    )}
                    {day.today && !isCompleted && (
                      <Text style={styles.todayBadge}>TODAY</Text>
                    )}
                  </View>
                  <Text style={styles.expandIcon}>
                    {isExpanded ? '−' : '+'}
                  </Text>
                </Pressable>

                {isExpanded && (
                  <View style={styles.dayDetail}>
                    {day.rationale && (
                      <View style={styles.rationaleBlock}>
                        <Text style={styles.rationaleLabel}>
                          AI RATIONALE
                        </Text>
                        <Text style={styles.rationaleText}>
                          {day.rationale}
                        </Text>
                      </View>
                    )}

                    {day.rest_day ? (
                      <View style={styles.restDetail}>
                        <Text style={styles.restMessage}>
                          Recovery is when your body adapts and gets stronger.
                          Rest days are strategically placed to optimize your
                          training response.
                        </Text>
                      </View>
                    ) : (
                      day.blocks.map((block) => (
                        <BlockView key={block.name} block={block} />
                      ))
                    )}
                  </View>
                )}
              </View>
            );
          })}

          <View style={styles.footer}>
            <Text style={styles.footerLabel}>ABOUT THIS PLAN</Text>
            <Text style={styles.footerText}>
              Your plan is generated by our AI coach, which analyzes your
              training history, recovery metrics, muscle group balance, and
              stated goals. The plan adapts dynamically — if you miss a day or
              overtrain, the AI adjusts upcoming sessions to keep you on track.
            </Text>
            <Text style={styles.footerText}>
              Each exercise is chosen for a reason: to address weak points,
              maintain strengths, or progressively overload key movements. Tap
              any day above to see the full reasoning.
            </Text>
          </View>
        </ScrollView>
      )}
    </View>
  );
}

function BlockView({ block }: { block: PlanBlock }) {
  const blockLabel = block.name.toUpperCase();
  const isMain = block.name === 'Main';

  return (
    <View style={[styles.blockContainer, isMain && styles.blockMain]}>
      <Text style={[styles.blockLabel, isMain && styles.blockLabelMain]}>
        {blockLabel}
      </Text>
      {block.exercises.map((ex, i) => (
        <ExerciseView key={`${ex.name}-${i}`} exercise={ex} isMain={isMain} />
      ))}
    </View>
  );
}

function ExerciseView({
  exercise,
  isMain,
}: {
  exercise: PlanExercise;
  isMain: boolean;
}) {
  const prescription = buildPrescription(exercise);

  return (
    <View style={styles.exerciseContainer}>
      <View style={styles.exerciseHeader}>
        <Text style={[styles.exerciseName, isMain && styles.exerciseNameMain]}>
          {exercise.name}
        </Text>
        {prescription && (
          <Text style={styles.exercisePrescription}>{prescription}</Text>
        )}
      </View>
      {exercise.coaching_tip && (
        <View style={styles.coachingTipRow}>
          <Text style={styles.coachingTipLabel}>TIP</Text>
          <Text style={styles.coachingTipText}>{exercise.coaching_tip}</Text>
        </View>
      )}
      {exercise.description && (
        <Text style={styles.exerciseDescription}>{exercise.description}</Text>
      )}
      {exercise.notes && (
        <Text style={styles.exerciseNotes}>{exercise.notes}</Text>
      )}
      <View style={styles.exerciseMetaRow}>
        {exercise.rpe_target != null && (
          <Text style={styles.exerciseMeta}>
            RIR {10 - exercise.rpe_target}
          </Text>
        )}
        {exercise.rest_seconds != null && (
          <Text style={styles.exerciseMeta}>
            {exercise.rest_seconds >= 60
              ? `${Math.round(exercise.rest_seconds / 60)} min rest`
              : `${exercise.rest_seconds}s rest`}
          </Text>
        )}
        {exercise.zone && (
          <Text style={styles.exerciseMeta}>Zone {exercise.zone}</Text>
        )}
      </View>
    </View>
  );
}

function buildPrescription(ex: PlanExercise): string | null {
  const parts: string[] = [];
  if (ex.sets && ex.rep_range) {
    parts.push(`${ex.sets}\u00D7${ex.rep_range}`);
  }
  if (ex.duration_minutes) {
    parts.push(`${ex.duration_minutes} min`);
  }
  if (ex.intervals) {
    parts.push(ex.intervals);
  }
  return parts.length > 0 ? parts.join(' \u2022 ') : null;
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#222222',
  },
  backBtn: {
    width: 80,
  },
  backText: {
    color: '#888888',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1,
  },
  headerTitle: {
    color: '#555555',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 3,
    textAlign: 'center',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyTitle: {
    color: '#555555',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 3,
    fontFamily: MONO,
    marginBottom: 16,
  },
  emptyText: {
    color: '#444444',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  scrollContent: {
    padding: 16,
  },
  planMeta: {
    borderWidth: 0.5,
    borderColor: '#222222',
    padding: 16,
    marginBottom: 20,
  },
  planName: {
    color: '#EAEAEA',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
    marginBottom: 4,
  },
  planType: {
    color: '#888888',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 2,
    fontFamily: MONO,
    marginBottom: 12,
  },
  aiLabel: {
    color: '#2ECC71',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 3,
    fontFamily: MONO,
    marginBottom: 8,
  },
  aiExplainer: {
    color: '#555555',
    fontSize: 12,
    lineHeight: 18,
  },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#1A1A1A',
  },
  dayRowToday: {
    backgroundColor: '#111511',
    borderLeftWidth: 2,
    borderLeftColor: '#2ECC71',
  },
  dayRowExpanded: {
    borderBottomWidth: 0,
  },
  dayInfo: {
    width: 60,
  },
  dayLabel: {
    color: '#888888',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 2,
    fontFamily: MONO,
  },
  dayLabelToday: {
    color: '#2ECC71',
  },
  dayDate: {
    color: '#444444',
    fontSize: 10,
    fontFamily: MONO,
    marginTop: 2,
  },
  daySession: {
    color: '#CCCCCC',
    fontSize: 13,
    fontFamily: MONO,
    flex: 1,
  },
  dayRest: {
    color: '#555555',
  },
  dayStatus: {
    width: 60,
    alignItems: 'flex-end',
  },
  checkmark: {
    color: '#2ECC71',
    fontSize: 14,
  },
  todayBadge: {
    color: '#2ECC71',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1,
    fontFamily: MONO,
  },
  expandIcon: {
    color: '#555555',
    fontSize: 18,
    fontWeight: '300',
    width: 24,
    textAlign: 'right',
  },
  dayDetail: {
    backgroundColor: '#0D0D0D',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#1A1A1A',
    marginBottom: 4,
  },
  rationaleBlock: {
    borderLeftWidth: 2,
    borderLeftColor: '#2ECC71',
    paddingLeft: 12,
    marginBottom: 16,
  },
  rationaleLabel: {
    color: '#2ECC71',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 2,
    fontFamily: MONO,
    marginBottom: 6,
  },
  rationaleText: {
    color: '#CCCCCC',
    fontSize: 13,
    lineHeight: 20,
    fontStyle: 'italic',
  },
  restDetail: {
    paddingVertical: 8,
  },
  restMessage: {
    color: '#888888',
    fontSize: 12,
    lineHeight: 18,
  },
  blockContainer: {
    marginBottom: 12,
  },
  blockMain: {
    borderWidth: 0.5,
    borderColor: '#1A1A1A',
    padding: 12,
  },
  blockLabel: {
    color: '#555555',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 2,
    fontFamily: MONO,
    marginBottom: 8,
  },
  blockLabelMain: {
    color: '#888888',
  },
  exerciseContainer: {
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#1A1A1A',
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exerciseName: {
    color: '#AAAAAA',
    fontSize: 12,
    fontFamily: MONO,
    flex: 1,
  },
  exerciseNameMain: {
    color: '#EAEAEA',
    fontSize: 13,
    fontWeight: '500',
  },
  exercisePrescription: {
    color: '#888888',
    fontSize: 11,
    fontFamily: MONO,
  },
  coachingTipRow: {
    flexDirection: 'row',
    marginTop: 6,
    paddingLeft: 8,
  },
  coachingTipLabel: {
    color: '#2ECC71',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1,
    fontFamily: MONO,
    marginRight: 8,
    marginTop: 1,
  },
  coachingTipText: {
    color: '#7EBF8E',
    fontSize: 11,
    lineHeight: 16,
    flex: 1,
  },
  exerciseDescription: {
    color: '#666666',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
    paddingLeft: 8,
  },
  exerciseNotes: {
    color: '#555555',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
    paddingLeft: 8,
    fontStyle: 'italic',
  },
  exerciseMetaRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
    paddingLeft: 8,
  },
  exerciseMeta: {
    color: '#555555',
    fontSize: 10,
    fontFamily: MONO,
    letterSpacing: 1,
  },
  footer: {
    borderTopWidth: 0.5,
    borderTopColor: '#222222',
    paddingTop: 20,
    marginTop: 16,
  },
  footerLabel: {
    color: '#555555',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 3,
    fontFamily: MONO,
    marginBottom: 12,
  },
  footerText: {
    color: '#444444',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
  },
});
